"""added cascading, account to transactions2

Revision ID: 62b5a483a3fb
Revises: 40bbd488dafc
Create Date: 2025-03-03 12:04:01.643920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b5a483a3fb'
down_revision: Union[str, None] = '40bbd488dafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
