"""added cascading, account to transactions3

Revision ID: 6d0cc8b11836
Revises: 62b5a483a3fb
Create Date: 2025-03-03 12:07:16.922801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0cc8b11836'
down_revision: Union[str, None] = '62b5a483a3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_to_account_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_from_account_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_from_account_fkey', 'transactions', 'accounts', ['from_account'], ['id'])
    op.create_foreign_key('transactions_to_account_fkey', 'transactions', 'accounts', ['to_account'], ['id'])
    # ### end Alembic commands ###
